import { describe, expect, it } from "vitest";
import { generateTypstCode } from "./typst-generator";
import { defaultSignatureData } from "./types";

describe("generateTypstCode", () => {
  it("brands generated source and escapes Typst control characters", () => {
    const data = structuredClone(defaultSignatureData);
    data.name = "Jane #Doe [Team]";

    const typst = generateTypstCode(data);

    expect(typst).toContain("Generated by EmailSmith");
    expect(typst).toContain("Jane \\#Doe \\[Team\\]");
  });

  it("normalizes bare links", () => {
    const data = structuredClone(defaultSignatureData);
    data.website = "example.com";
    data.ctaText = "Book a meeting";
    data.ctaUrl = "calendar.example.com/jane";

    const typst = generateTypstCode(data);

    expect(typst).toContain("https://example.com");
    expect(typst).toContain("https://calendar.example.com/jane");
  });
});
